theme: jekyll-theme-tactile
title: Welcome to Will Newbegin's homepage!
description: Hi all! I'm Will Newbegin, a rising senior at Lehigh University. I'm currently taking COMM 165, and this is my 'home base' for the class.
